Alpaca - Backported compatibility with latest Fabric Loader
Chocohead/OptiFabric pull request #804
Opened 2022-07-24 12:19 UTC by Sjouwer

- Fixes OptiFine's properly
- Fixes compatibility issues with Fabric Loader 0.12 - 0.14
- Updated Loom & Gradle

fixes #708

2022-07-24 13:41 UTC, Sjouwer commented
Not sure which version you'd like for this one
I put it on 1.1.0, though found out this has already been used in the past for 1.16 beta's

2022-07-24 22:37 UTC, Chocohead commented
Ideally it would be 1.1.0 but like you say that was used for 1.16, I don't mind it being 1.0.2

2022-07-25 13:05 UTC, Sjouwer commented
Force push was just to make the message a bit more clear, no code changes, Forgot that would show up here too, oh well.
In any case, this should be it I believe.

2022-08-10 22:32 UTC, Chocohead requested changes
Just a pair of things I noticed doing one last check

2022-08-10 22:32 UTC, Chocohead commented on src/main/resources/optifabric.optifine.mixins.json
> +    "MixinDefaultResourcePack"
This is duplicated in `optifabric.mixins.json`; I think Mixin will just ignore it, but probably best that it's only in the one

2022-08-10 22:32 UTC, Chocohead commented on src/main/java/me/modmuss50/optifabric/mod/OptifineSetup.java
> +			return (Path) FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJar");
If you're depending on Loader 0.12 anyway you might as well set 0.12.3 as the minimum then you won't need the catch block (as the object share is always present)

2022-08-12 12:04 UTC, Sjouwer commented on src/main/resources/optifabric.optifine.mixins.json
> +    "MixinDefaultResourcePack"
Ah I think I know how that happened, good catch though, I'll remove one

2022-08-12 12:20 UTC, Sjouwer commented on src/main/java/me/modmuss50/optifabric/mod/OptifineSetup.java
> +			return (Path) FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJar");
Now that I think about it, I'm not entirely sure why I upped the dependency to 0.12. I know that I did the same for 1.14, so I figured it was needed for some reason. I wouldn't be surprised if it was only needed at first, but after backporting more that it was no longer an issue.
I'm thinking it might be better to keep the catch block as is and only put the dependency back to `fabricloader": ">=0.8.0` same as Llama (should probably be changed for Vicuña too). I can imagine many 1.14 and 1.15 installs still use older versions of the loader.

What's your opinion on this?

2022-08-13 01:04 UTC, Chocohead commented on src/main/java/me/modmuss50/optifabric/mod/OptifineSetup.java
> +			return (Path) FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJar");
If you can make it work on a wider version range that makes things simpler for end users who have existing (old) installs and would like drop-in updates.

2022-08-15 13:32 UTC, Sjouwer commented
I did some testing and both Vicuña and Alpaca are able to run with fabric loader 0.9.0 or later.
Could you adjust this for the Vicuña, or do you prefer it if I'd make another PR?

2022-08-17 22:48 UTC, Chocohead commented
Might as well make another PR for Vicuña, avoids it being forgotten

As for this one, I think it's good to go now

2022-08-17 22:49 UTC, merged